version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    command: yarn run dev
    volumes:
      - ./frontend:/app:cached
      - node_modules:/node_modules
    working_dir: "/app"
    ports:
      - "3000:3000"
    tty: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
volumes:
  node_modules: