=begin
teamJava

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def get_follow_lists_user_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_followed_lists_user_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_message_room_lists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_messages_message_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_post_lists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_posts_post_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_users_user_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_bookmark
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_evaluates
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_follows
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_login
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_message_rooms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_messages
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_posts
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_register
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_posts_post_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_users_user_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
