=begin
teamJava

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'GET', '/follow-lists/{user-id}', controller_name: 'default', action_name: 'get_follow_lists_user_id'
  add_openapi_route 'GET', '/followed-lists{user-id}', controller_name: 'default', action_name: 'get_followed_lists_user_id'
  add_openapi_route 'GET', '/message-room-lists', controller_name: 'default', action_name: 'get_message_room_lists'
  add_openapi_route 'GET', '/messages/{message-room-id}', controller_name: 'default', action_name: 'get_messages_message_id'
  add_openapi_route 'GET', '/post-lists', controller_name: 'default', action_name: 'get_post_lists'
  add_openapi_route 'GET', '/posts/{post-id}', controller_name: 'default', action_name: 'get_posts_post_id'
  add_openapi_route 'GET', '/users/{user-id}', controller_name: 'default', action_name: 'get_users_user_id'
  add_openapi_route 'POST', '/bookmark', controller_name: 'default', action_name: 'post_bookmark'
  add_openapi_route 'POST', '/evaluates', controller_name: 'default', action_name: 'post_evaluates'
  add_openapi_route 'POST', '/follows', controller_name: 'default', action_name: 'post_follows'
  add_openapi_route 'POST', '/login', controller_name: 'default', action_name: 'post_login'
  add_openapi_route 'POST', '/message-rooms', controller_name: 'default', action_name: 'post_message_rooms'
  add_openapi_route 'POST', '/messages', controller_name: 'default', action_name: 'post_messages'
  add_openapi_route 'POST', '/posts', controller_name: 'default', action_name: 'post_posts'
  add_openapi_route 'POST', '/register', controller_name: 'default', action_name: 'post_register'
  add_openapi_route 'PUT', '/posts/{post-id}', controller_name: 'default', action_name: 'put_posts_post_id'
  add_openapi_route 'PUT', '/users/{user-id}', controller_name: 'default', action_name: 'put_users_user_id'
end
