=begin
teamJava

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class GetUsersUserId200Response < ApplicationRecord
  validates_presence_of :user_name
  validates_presence_of :comment
  validates_presence_of :user_icon
  validates_presence_of :evaluation

end
