=begin
teamJava

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class GetPostsPostId200Response < ApplicationRecord
  validates_presence_of :product_title
  validates_presence_of :product_image
  validates_presence_of :comment
  validates_presence_of :tag
  validates_presence_of :status

end
