=begin
teamJava

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class PostPostsRequest < ApplicationRecord
  validates_presence_of :product_title
  validates_presence_of :product_image

end
