=begin
teamJava

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "get_follow_lists_user_id_200_response".pluralize.to_sym, id: false do |t|
      t.Object :follow_user_id
      t.Object :follow_user_name
      t.Object :follow_user_icon

      t.timestamps
    end

    create_table "get_followed_lists_user_id_200_response".pluralize.to_sym, id: false do |t|
      t.Object :followed_user_id
      t.Object :followed_user_name
      t.Object :followed_user_icon

      t.timestamps
    end

    create_table "get_message_room_lists_200_response".pluralize.to_sym, id: false do |t|
      t.Object :latest_message
      t.Object :user_id
      t.Object :user_name
      t.Object :user_icon

      t.timestamps
    end

    create_table "get_messages_message_id_200_response".pluralize.to_sym, id: false do |t|
      t.Object :message
      t.Object :sent_user_id
      t.Object :user_icon
      t.Object :create_at

      t.timestamps
    end

    create_table "get_post_lists_200_response".pluralize.to_sym, id: false do |t|
      t.Object :product_name
      t.Object :product_image
      t.Object :user_name
      t.Object :user_icon
      t.Object :status
      t.Object :create_at

      t.timestamps
    end

    create_table "get_post_lists_request".pluralize.to_sym, id: false do |t|
      t.Object :search_way
      t.Object :search_word

      t.timestamps
    end

    create_table "get_posts_post_id_200_response".pluralize.to_sym, id: false do |t|
      t.Object :product_title
      t.Object :product_image
      t.Object :comment
      t.Object :tag
      t.Object :status

      t.timestamps
    end

    create_table "get_users_user_id_200_response".pluralize.to_sym, id: false do |t|
      t.Object :user_name
      t.Object :comment
      t.Object :user_icon
      t.Object :evaluation

      t.timestamps
    end

    create_table "post_bookmark_request".pluralize.to_sym, id: false do |t|
      t.Object :user_id
      t.Object :product_id

      t.timestamps
    end

    create_table "post_evaluates_request".pluralize.to_sym, id: false do |t|
      t.Object :user_id
      t.Object :rated_user_id
      t.Object :evaluate
      t.Object :comment

      t.timestamps
    end

    create_table "post_follows_request".pluralize.to_sym, id: false do |t|
      t.Object :follow_id
      t.Object :followed_id

      t.timestamps
    end

    create_table "post_login_request".pluralize.to_sym, id: false do |t|
      t.Object :email
      t.Object :password

      t.timestamps
    end

    create_table "post_message_rooms_request".pluralize.to_sym, id: false do |t|
      t.Object :my_user_id
      t.Object :user_id
      t.Object :product_id

      t.timestamps
    end

    create_table "post_messages_request".pluralize.to_sym, id: false do |t|
      t.Object :message_room_id
      t.Object :sent_user_id
      t.Object :message

      t.timestamps
    end

    create_table "post_posts_request".pluralize.to_sym, id: false do |t|
      t.Object :product_title
      t.Object :product_image
      t.Object :comment
      t.Object :tag

      t.timestamps
    end

    create_table "post_register_201_response".pluralize.to_sym, id: false do |t|
      t.Object :user_id
      t.Object :user_name

      t.timestamps
    end

    create_table "post_register_400_response".pluralize.to_sym, id: false do |t|
      t.Object :message

      t.timestamps
    end

    create_table "post_register_request".pluralize.to_sym, id: false do |t|
      t.Object :user_name
      t.Object :email
      t.Object :password

      t.timestamps
    end

    create_table "put_posts_post_id_request".pluralize.to_sym, id: false do |t|
      t.Object :product_title
      t.Object :product_image
      t.Object :comment
      t.Object :tag
      t.Object :status

      t.timestamps
    end

    create_table "put_users_user_id_request".pluralize.to_sym, id: false do |t|
      t.Object :user_id
      t.string :edit

      t.timestamps
    end

    create_table "put_users_user_id_request_edit".pluralize.to_sym, id: false do |t|
      t.Object :user_name
      t.Object :email
      t.Object :user_icon
      t.Object :school
      t.Object :comment

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.Object :id
      t.Object :name
      t.Object :email
      t.Object :icon

      t.timestamps
    end

  end
end
